// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ASPCoreMVC.Models;

public partial class AbrilAnimalesContext : DbContext
{
    public AbrilAnimalesContext(DbContextOptions<AbrilAnimalesContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Animal> Animals { get; set; }

    public virtual DbSet<TipoAnimal> TipoAnimals { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Animal>(entity =>
        {
            entity.HasKey(e => e.IdAnimal);

            entity.ToTable("Animal");

            entity.Property(e => e.NombreAnimal)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Raza)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.RIdTipoAnimal).HasColumnName("RIdTipoAnimal");

            entity.HasOne(d => d.RIdTipoAnimalNavigation).WithMany(p => p.Animals)
                .HasForeignKey(d => d.RIdTipoAnimal)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Animal_TipoAnimal");
        });

        modelBuilder.Entity<TipoAnimal>(entity =>
        {
            entity.HasKey(e => e.IdTipoAnimal);

            entity.ToTable("TipoAnimal");

            entity.Property(e => e.TipoDescripcion)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}