// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASPCoreMVC.Models;

public partial class Animal
{
    public int IdAnimal { get; set; }

    public string NombreAnimal { get; set; }

    public string Raza { get; set; }

    public int RIdTipoAnimal { get; set; }

    public DateOnly? FechaNacimiento { get; set; }

    public virtual TipoAnimal RIdTipoAnimalNavigation { get; set; }
}