// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ASPCoreMVC.Models;

public partial class TipoAnimal
{
    public int IdTipoAnimal { get; set; }
    public string TipoDescripcion { get; set; }

    // Relación con animales
    public virtual ICollection<Animal> Animals { get; set; } = new List<Animal>();
}
